import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { FaCoffee } from "react-icons/fa";
import { Player } from "@lottiefiles/react-lottie-player";
import coffeeAnimation from "../assets/Coffee-Barista.json";
import backgroundImage from "../assets/mocha.jpeg";
const Login = () => {
    return (_jsxs("div", { className: "min-h-screen flex items-center justify-center bg-cover bg-center", style: { backgroundImage: `url(${backgroundImage})` }, children: [_jsx("div", { className: "absolute inset-0 bg-[#f3ece6]/30 backdrop-blur-sm z-0" }), _jsxs("div", { className: "relative z-10 flex flex-col md:flex-row items-center bg-white/90 rounded-2xl shadow-2xl overflow-hidden max-w-5xl w-full backdrop-blur-md", children: [_jsx("div", { className: "hidden md:flex w-full md:w-1/2 justify-center items-center p-8 bg-[#f9f5f1]", children: _jsx(Player, { autoplay: true, loop: true, src: coffeeAnimation, style: { height: "320px", width: "320px" } }) }), _jsxs("div", { className: "w-full md:w-1/2 p-10", children: [_jsxs("div", { className: "flex flex-col items-center mb-6", children: [_jsx(FaCoffee, { className: "text-5xl text-[#6b4226] mb-2" }), _jsx("h2", { className: "text-3xl font-bold text-[#4b2e2e]", children: "Welcome Back" }), _jsx("p", { className: "text-[#7c5b45] text-sm mt-1", children: "Login to enjoy your favorite brew \u2615" })] }), _jsxs("form", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-[#5a3e2b] font-medium mb-1", children: "Email" }), _jsx("input", { type: "email", placeholder: "coffee@love.com", className: "w-full px-4 py-2 border border-[#c8b5a0] rounded-lg focus:outline-none focus:ring-2 focus:ring-[#b08b68] bg-[#fcf9f6]" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-[#5a3e2b] font-medium mb-1", children: "Password" }), _jsx("input", { type: "password", placeholder: "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022", className: "w-full px-4 py-2 border border-[#c8b5a0] rounded-lg focus:outline-none focus:ring-2 focus:ring-[#b08b68] bg-[#fcf9f6]" })] }), _jsx("button", { type: "submit", className: "w-full bg-[#8c5c3c] text-white py-2 rounded-lg hover:bg-[#724831] transition", children: "Login" })] }), _jsxs("div", { className: "text-sm text-center mt-4 text-[#5a3e2b]", children: ["Don\u2019t have an account?", _jsx(Link, { to: "/signUp", className: "text-[#a76c45] hover:underline ml-1", children: "Sign up" })] })] })] })] }));
};
export default Login;
